### ISSUE TITLE
Excalibur when used, the other players can't see if it was used

### ISSUE THREAD

**Issue by DaniPPereira** [Razdva122/avalon#2]
When someone uses the excalibur, the other players in the room can't see if it was used or not(sometimes it works, but it is not consistent)

**Comment by Razdva122** [comment]
@DaniPPereira 

According to the rules, the result of using excalibur is known only by the person who used it. And of course the one on whom it was applied. You can tell other players about the result of using it, but you can also lie in the same way.

For example, 2 minions in a mission, both press fail, and at the same time, one minion uses excalibur on the second. There is 1 fail in the mission and they can lie that it is a fail because of the excalibur
